package:
  name: cbc_bin
  version: "2.7.5" [win64]
  version: "2.4.0" [linux64]
  version: "2.3.2" [osx]

source:
  fn: Cbc-2.7.5-win64-intel11.1.zip [win64]
  url: http://www.coin-or.org/download/binary/Cbc/Cbc-2.7.5-win64-intel11.1.zip [win64]
  md5: defa73718a8c77de2adb871edec97470 [win64]

  fn: Cbc-2.4.0-linux-x86_64-gcc4.3.2-parallel.tgz [linux64]
  url: http://www.coin-or.org/download/binary/Cbc/Cbc-2.4.0-linux-x86_64-gcc4.3.2-parallel.tgz [linux64]
  md5: b8c26f9c47344be50b7954096439978c [linux64]

  fn: Cbc-2.3.2-mac-osx-x86_64-gcc4.3.3-parallel.tgz [osx]
  url: http://www.coin-or.org/download/binary/Cbc/Cbc-2.3.2-mac-osx-x86_64-gcc4.3.3-parallel.tgz [osx]
  md5: 6f64c2c50341b5ecbe5a97a1509155fb [osx]

build:
  number: {{ environ.get("APPVEYOR_BUILD_NUMBER", 1) }} [win]

about:
  home: https://projects.coin-or.org/Cbc
  license: Eclipse Public License (EPL)
  summary: 'Software package for mixed-integer linear optimization'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
