package:
  name: ipopt_bin
  version: "3.11.1" [win64 or osx]
  version: "3.7.1" [linux64]

source:
  fn: Ipopt-3.11.1-win64-intel13.1.zip [win64]
  url: http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-win64-intel13.1.zip [win64]
  md5: c8c1e3a26da21aa9f061353981556a52 [win64]

  fn: Ipopt-3.7.1-linux-x86_64-gcc4.3.2.tgz [linux64]
  url: http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.7.1-linux-x86_64-gcc4.3.2.tgz [linux64]
  md5: b9b6c656ed347f9cd173d7de6878ff33 [linux64]

  fn: Ipopt-3.11.1-mac-osx-x86_64-gcc4.5.3.tgz [osx]
  url: http://www.coin-or.org/download/binary/Ipopt/Ipopt-3.11.1-mac-osx-x86_64-gcc4.5.3.tgz [osx]
  md5: 69d74f98b1874dacb0be4506646c698f [osx]

build:
  number: {{ environ.get("APPVEYOR_BUILD_NUMBER", 1) }} [win]

about:
  home: https://projects.coin-or.org/Ipopt
  license: Eclipse Public License (EPL)
  summary: 'Software package for large-scale nonlinear optimization'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
