# A metapackage for COIN-OR solvers

package:
  name: coinor_bin
  version: 1.0

requirements:
  run:
    - ipopt_bin
    - cbc_bin

about:
  license: BSD License
  summary: 'A metapackage for COIN-OR solvers'
